<<<<<<< HEAD
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
=======
import '../styles/globals.css'
import { Inter } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'OvaSite',
  description: 'Your monitoring, evaluation and Data collection solution',
>>>>>>> origin/axios-integration
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body className={inter.className}>{children}</body>
=======
      <body>
      
        {children}
       
        </body>
>>>>>>> origin/axios-integration
    </html>
  )
}
