<<<<<<< HEAD
import '../styles/globals.css'
import { Inter } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'OvaSite',
  description: 'Your monitoring, evaluation and Data collection solution',
=======
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
>>>>>>> 7a23002de685b7609829bc0b1d9b681d4a07eed8
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body>
      
        {children}
       
        </body>
=======
      <body className={inter.className}>{children}</body>
>>>>>>> 7a23002de685b7609829bc0b1d9b681d4a07eed8
    </html>
  )
}
